version: '3.8'

services:
  api:
    build: .
    container_name: linkedin_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Sincroniza os arquivos locais com o container para o hot-reload funcionar
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    dns:
      - 8.8.8.8
      - 1.1.1.1

  db:
    image: postgres:16-alpine
    container_name: linkedin_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: